### PR TITLE
Use I18n and add Japanese locale.

### PR DESCRIPTION
**Pull request by tomoyuki28jp**
I made changes based on the work made by @joelmeyerhamme ( https://github.com/joelmeyerhamme/ice_cube/tree/international ).
https://github.com/seejohnrun/ice_cube/issues/68

### CODE REVIEW

**Comment by emilkarl** [comment]
What is the status of this? Will it be possible to use I18n?

**Comment by dgilperez** [comment]
Hey @emilkarl, [this PR](https://github.com/seejohnrun/ice_cube/pull/273) is working. I'm using that code in a side project, though it's not battle-tested.

I'm not sure why this PR is not getting attention.

**Comment by emilkarl** [comment]
Cool @dgilperez. Maybe I am stupid but how do I add a PR in the Gemfile?

**Comment by dgilperez** [comment]
You can refer to a particular branch or commit in your Gemfile like this: 

    gem 'ice_cube', github: 'dgilperez/ice_cube', branch: 'pull-259'
    # or
    gem 'ice_cube', github: 'dgilperez/ice_cube', ref: '4926bf972f7c24c280e652dbac79348e5b9b9744'

Also, peeking at the [network graph](https://github.com/dgilperez/ice_cube/network) from my fork, I see the nice guys at gocardless have continued work on that PR, adding some locales and a few other goodies. It may a better replacement, what do you think @isaacseymour? Is your fork production ready?

**Comment by emilkarl** [comment]
Awesome. I'll take a look at that too then!

**Comment by isaacseymour** [comment]
Yep, we've been using the gocardless fork in production, it's not hugely
different. Would be great to be back on the official RubyGems version
though!

**Comment by dgilperez** [comment]
Thanks @isaacseymour !!! Giving it a try ...

**Comment by avit** [comment]
@tomoyuki28jp Sorry, I have been away from this project for some time. I18n was added as an optional dependency in the meantime, and I would be happy to merge your contribution for Japanese translation.

If you still find it useful, please see the latest master branch and add your jp.yml on it. We can reopen this PR or make a new one.

**Pull request closed without merging**
