### PR TITLE
Add i18n

### PR DESCRIPTION
**Pull request by greysteil**
An amalgamation of:
- @tomoyuki28jp's https://github.com/seejohnrun/ice_cube/pull/259
- @dgilperez's work over at https://github.com/dgilperez/ice_cube
- @isaacseymour's work at https://github.com/dgilperez/ice_cube/pull/1

Specs should pass and this should be :ok_hand: to go...

### CODE REVIEW

**Comment by seejohnrun** [comment]
:+1:
Released as version `0.13.1`

Thanks everyone!

**Comment by martinstreicher** [comment]
Is there something required to use 0.13.1? I am getting ...

```
 expected: "Yearly"
            got: "translation missing: en.ice_cube.each_year"
```

In some of my own tests.

**Comment by martinstreicher** [comment]
This is another instance:

```
  expected: "Every 2 years"
            got: "translation missing: en.ice_cube.each_year"
```

**Comment by martinstreicher** [comment]
And one other issue that appears a lot in my specs...

```
     TypeError:
       no implicit conversion of Symbol into Integer
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/builders/string_builder.rb:24:in `[]'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/builders/string_builder.rb:24:in `block in to_s'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/builders/string_builder.rb:17:in `each'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/builders/string_builder.rb:17:in `to_s'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/validated_rule.rb:78:in `to_s'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/schedule.rb:317:in `block in to_s'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/schedule.rb:317:in `map'
     # /Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/ice_cube-0.13.1/lib/ice_cube/schedule.rb:317:in `to_s'
```

**Comment by martinstreicher** [comment]
Digging in a little on the latter to see if I can relay more info.

**Comment by martinstreicher** [comment]
On line 24...

```
(byebug) ap IceCube::I18n.t('ice_cube.string.format')
"translation missing: en.ice_cube.string.format"
```

**Comment by seejohnrun** [comment]
@martinstreicher odd - I'm able to do the following and get 'every 2 years'

``` ruby
require 'ice_cube'

schedule = IceCube::Schedule.new Time.now
schedule.rrule IceCube::Rule.yearly(2)
puts schedule.to_s
```

any more detail you can provide? cc / @greysteil

**Comment by martinstreicher** [comment]
Odd. I get this when running that small snippet. What version of i18n do you have? I am using Ruby 2.2.3. 

```
/Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!': :en is not a valid locale (I18n::InvalidLocale)
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/i18n-0.7.0/lib/i18n.rb:151:in `translate'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/i18n.rb:4:in `t'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/validations/yearly_interval.rb:35:in `build_s'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/validated_rule.rb:75:in `block (2 levels) in to_s'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/validated_rule.rb:74:in `each'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/validated_rule.rb:74:in `block in to_s'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/validated_rule.rb:73:in `each'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/validated_rule.rb:73:in `to_s'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/schedule.rb:317:in `block in to_s'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/schedule.rb:317:in `map'
	from /Users/strike/.rvm/gems/ruby-2.2.3@duke_prompt/gems/ice_cube-0.13.1/lib/ice_cube/schedule.rb:317:in `to_s'
	from eh.rb:5:in `<main>'
```

**Comment by seejohnrun** [comment]
This is `0.7.0` as well :/

Here's my `Gemfile.lock` for reference:

```
PATH
  remote: .
  specs:
    ice_cube (0.13.1)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    diff-lcs (1.1.3)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.8.3)
    rake (10.4.2)
    rspec (2.12.0)
      rspec-core (~> 2.12.0)
      rspec-expectations (~> 2.12.0)
      rspec-mocks (~> 2.12.0)
    rspec-core (2.12.2)
    rspec-expectations (2.12.1)
      diff-lcs (~> 1.1.3)
    rspec-mocks (2.12.2)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (>= 3.0.0)
  i18n
  ice_cube!
  rake
  rspec (~> 2.12.0)
  tzinfo
```

**Comment by martinstreicher** [comment]
That's a pretty simple list. I have tons of other things in mine, including Rails. Let me do some digging. This was not an issue with 0.13.0, but I think from the commits for 0.13.1 that i18n was added for that release.

**Comment by seejohnrun** [comment]
That's correct
This PR's diff is basically the new changes

**Comment by martinstreicher** [comment]
Stupid question: If I look at the 0.13.1 gem installed locally after running `bundle install`, I do not see a _config_ directory. Should I be installing from the master branch?

**Comment by martinstreicher** [comment]
If I pull down the tar file for the release, the subdir _config_ is there.

**Comment by seejohnrun** [comment]
Ahh :) I think this may be it - the config path should be added to the gemspec
Can you try installing `0.13.2` (just released)

**Comment by martinstreicher** [comment]
0.13.2 fixes the issue. The _config_ directory is there and the gem works.

**Comment by seejohnrun** [comment]
Great sorry for the inconvenience @martinstreicher and thanks for the great report

**Comment by dgilperez** [comment]
:clap: :tada: :smile: 

Thanks @seejohnrun for merging.

**Comment by seejohnrun** [comment]
thank you @dgilperez  :)

**Comment by martinstreicher** [comment]
@seejohnrun No problem. Thanks to rspec and a very large suite for my IceCube coding. (Now I just need to figure out why 8 of my tests always break when run on a machine set in the UTC time zone!)

**Pull request merged**
