### PR TITLE
Add pt-BR (Brazilian Portuguese) locale

### PR DESCRIPTION
**Pull request by easybills-admin**

### CODE REVIEW

**Comment by seejohnrun** [comment]
Thanks!

**Comment by easybills-admin** [comment]
@seejohnrun thanks for merging it so fast! 😄

**Comment by easybills-admin** [comment]
@seejohnrun when are you planning to bump the version? Thanks.

**Comment by avit** [comment]
@easybills-admin we just released 0.16 last week, there is a bug that needs investigation before the next release. Hopefully we can include this in 0.17 by next week.

**Pull request merged**
