### PR TITLE
Raise an ArgumentError if given an empty ical string

### PR DESCRIPTION
**Pull request by seejohnrun**

### CODE REVIEW

**Comment by Dorian** [comment]
Yup, basically random strings too should not be throwing `NoMethodError`(in my usecase the rule is user-provided and I want to validate it).

Other examples:

- `IceCube::Schedule.from_ical('RRULE::A')` -> `TypeError: 1 is not a symbol nor a string`
- `IceCube::Schedule.from_ical('RRULE:FREQ')` -> `NoMethodError: undefined method `strip!' for nil:NilClass`
- `IceCube::Schedule.from_ical('RRULE:FREQ=WEKLY;WKST=SU')` -> `NoMethodError: undefined method `wekly' for IceCube::Rule:Class` (seems like a possible security issue)

Those are correct:

- `IceCube::Schedule.from_ical('RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR;WKST=SE')` -> `ArgumentError: Invalid day: SE`

Wrong exception:

- `IceCube::Schedule.from_ical('RRULE:FREQ=WEEKLY;BDAY=MO,WE,FR;WKST=SU')`
-> `RuntimeError: Invalid or unsupported rrule command: BDAY`. Should be `ArgumentError` I think.

**Comment by Dorian** [comment]
Another one:

- `IceCube::Schedule.from_ical('RRULE:FREQ=to_yaml')` -> `NoMethodError: undefined method `write' for 1:Fixnum`

**Comment by seejohnrun** [comment]
Thanks @Dorian 
I'm merging this, and merged #368 to address the validation issue in your follow-up comment above.

Would you mind creating issues for remaining parsing errors you've mentioned?

**Comment by Dorian** [comment]
@seejohnrun Done there :) https://github.com/seejohnrun/ice_cube/pull/373 (I'm happy to see most of them were actually already fixed, nice!)

**Pull request merged**
