### PR TITLE
Issues/50 from ical, cleaned up

### PR DESCRIPTION
**Pull request by wvengen**
Cleanup of #226.

Squashed all commits into one, removed non-ical changes, unbroke tests, and committed. Sorry to have lost all the contributors, but it was too unwieldy to rebase. Credits to @skyporter @jgauby @btucker @spra85.

I hope this helps in getting iCal parsing finally merged.

### CODE REVIEW

**Comment by airblade** [comment]
Just wondering whether there's an ETA on merging this (or something similar)?

**Comment by bconway** [comment]
Would it be possible to support RDATE as a SingleOccurrenceRule? I just realized this patchset does not, which is not ideal.

**Comment by galatians** [comment]
We're using @wvengen 's fork in production and it works great.

**Comment by mgold** [comment]
I also would find this quite useful.

**Comment by jbat** [comment]
+1

**Comment by jbat** [comment]
User @wvengen  fork in production now as well

**Comment by mib32** [comment]
:kiss: :kiss: :kiss: 
i was really needed that

**Comment by wvengen** [comment]
Thank you!

**Pull request merged**
