### PR TITLE
Option to include prior occurrences with overlapping duration

### PR DESCRIPTION
**Pull request by jopotts**
Adding an option on schedule methods to include occurrences whose duration intersects a time window. Issue #154

https://github.com/seejohnrun/ice_cube/issues/154

### CODE REVIEW

**Comment by jopotts** [comment]
I opted for a simple defaulted option on the schedule methods. It's not as descriptive as what was proposed in [this thread](https://github.com/seejohnrun/ice_cube/issues/154) but it seemed to fit in with the rest of the code better the way I've done it, and a named param might reduce compatibility with older Rubys?

**Comment by Chosko** [comment]
I need this too. It would be great to have it merged..

**Comment by Chosko** [comment]
@seejohnrun any chance to see this merged?

**Comment by jopotts** [comment]
@avit It's well covered by tests and has been in production for us for months. No problems. It would be great to get it merged.

@Chosko Thanks for pushing for the merge.

**Comment by Chosko** [comment]
I use it in production too.. And it works great

**Comment by seejohnrun** [comment]
This is cool! definitely down to merge
Is it worth having `spans` as an option in an option hash so it's more clear?

ie: `spans: true`

**Comment by jopotts** [comment]
You're right. Much neater. I've updated the PR. Not sure what's going on with the Travis failures. Tests pass ok. Looking forward to the merge. Thanks!

**Comment by seejohnrun** [comment]
Thanks all - will be out as part of 0.14.0

**Pull request merged**
